version: '3'
services:
  restapi:
    build:
      context: ./restapi-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  celery-worker:
    build:
      context: ./tasks
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
