version: '3'

services:
  flaskapp:
    build:
      context: ./
      dockerfile: dockerfile.fla
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celeryworker

  celeryworker:
    build:
      context: ./
      dockerfile: dockerfile.cel
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
