# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . tasks/

# Run the Celery worker when the container starts
CMD ["celery", "-A", "tasks.celery_worker", "worker", "--loglevel=info"]
